name: three_dish_double_scanner
description: "3Dish double Scanner App."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1+1

environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  loading_animation_widget: ^1.2.1
  flutter_gen: ^5.8.0
  flutter_reactive_ble: ^5.3.1
  provider: ^6.1.2
  camera: ^0.10.5+9
  path_provider: ^2.1.2


  cupertino_icons: ^1.0.6
  gal: ^2.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0





flutter:
  uses-material-design: true
  generate: true

